version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_onbording
    restart: always # Restart this container if it fails
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    ports:
      - ${MYSQL_PORT}:3306 # Host port : Container port
