version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_onboarding
    restart: always # Restart this container if it fails
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306 # Host port : Container port
